export const SITE = {
  website: "https://guanxingcareer.com/",
  author: "观星哥",
  profile: "https://satnaing.dev/",
  desc: "深拆财务职场底层逻辑，为财务人提供专业职业规划与进阶策略。",
  title: "观星哥｜财务职场进化论",
  ogImage: "astropaper-og.jpg",
  lightAndDarkMode: true,
  postPerIndex: 6,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: false,
  showBackButton: true,
  editPost: {
    enabled: true,
    text: "Edit page",
    url: "https://github.com/satnaing/astro-paper/edit/main/",
  },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "zh-CN",
  timezone: "Asia/Shanghai",
} as const;
